CREATE TABLE IF NOT EXISTS `app-store-simulation.data.user-interactions-table` (
  generation_timestamp TIMESTAMP OPTIONS(
    description = "Unix timestamp (microseconds since epoch) when the event was generated by the publisher."
  ),
  event_id STRING OPTIONS(
    description = "Unique identifier for the event (UUID format)."
  ),
  event_timestamp TIMESTAMP OPTIONS(
    description = "Unix timestamp (microseconds since epoch) of when the event occurred in the user's timezone."
  ),
  user_id STRING(36) OPTIONS(
    description = "Identifier for the user."
  ),
  session_id STRING(36) OPTIONS(
    description = "Identifier for the user's session."
  ),
  event_type STRING(36) OPTIONS(
    description = "The type of interaction."
  ),
  app_id STRING(36) OPTIONS(
    description = "Identifier for the application."
  ),
  device_type STRING(36) OPTIONS(
    description = "User's device type."
  ),
  os_version STRING,
  country_code STRING(3) OPTIONS(
    description = "Operating system version, e.g., 'iOS 17.1' or 'Android 14'."
  ),
  event_details JSON OPTIONS(
    description = "Three-letter country code, e.g., 'IND', 'CHN', 'IRN'."
  )
) PARTITION BY
  -- Partitioning by day is a best practice for managing large time-series tables
  DATE(event_timestamp) OPTIONS(
    description = "A JSON string representing event-specific data.",
    labels = [("source", "pubsub"), ("content", "user_events")]
  );
